### ISSUE TITLE
When use "npm install hexo-symbols-count-time --save" to update this plugin now, it,s still the old version(0.3.2), but not the latest version(0.4.0) [fix added]

### ISSUE THREAD

**Issue by AlanKeene** [theme-next/hexo-symbols-count-time#12]
When I use `npm install hexo-symbols-count-time --save` to update this plugin now , it's still the old version of `0.3.2` to download in my terminal，but not the latest version of `0.4.0`.
```
$ npm install hexo-symbols-count-time --save

+ hexo-symbols-count-time@0.3.2
added 1 package in 10.723s

```

Has it updated to the npm ?

**Comment by ivan-nginx** [comment]
IDK how can i help u because current package appear `0.4.0` version:

https://github.com/theme-next/hexo-symbols-count-time/blob/ade60c6e3ee8370e477708ab94d68e2c1252733a/package.json#L1-L8

Maybe need first uninstall old and install new?

**Comment by ivan-nginx** [comment]
Fixed for now, check it.

**Comment by ivan-nginx** [comment]
@AlanKeene latest patched version for now is `0.4.2`. I just tested installation and it's work fine. Try again, please.

**Comment by AlanKeene** [comment]
@ivan-nginx 
What I got is still the version of 0.3.2.
```
$ npm install hexo-symbols-count-time --save
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ hexo-symbols-count-time@0.3.2
added 1 package in 24.958s

```

**Comment by ivan-nginx** [comment]
@AlanKeene 
Try to remove old version and install new:

```
$ npm uninstall hexo-symbols-count-time --save
$ npm install hexo-symbols-count-time --save
```

U can see [my log above](https://github.com/theme-next/hexo-symbols-count-time/issues/12#issuecomment-381649455).
