### ISSUE TITLE
The web reading time can not show correctly.

### ISSUE THREAD

**Issue by xiekeyi98** [theme-next/hexo-symbols-count-time#13]
![image](https://user-images.githubusercontent.com/7782671/40307823-95e36738-5d36-11e8-8695-49cbd1f6c50a.png)

[My blog](xiekeyi98.com)

As the picture shown , the Web reading time can't show correctly , and What can I do for it ?
( I try to modify the *.swig , but not find anything help )

I have no alternative to do other thing , but bother someone here. 

Thanks a lot for everyone help me .

**Comment by ivan-nginx** [comment]
Fixed in [v0.4.3 release](https://github.com/theme-next/hexo-symbols-count-time/releases/tag/v0.4.3).

If solved, close it please.

**Comment by xiekeyi98** [comment]
Perfect solved . 
Thanks very much.
