### ISSUE TITLE
An error occurs when the article has code

### ISSUE THREAD

**Issue by Love-H** [theme-next/hexo-symbols-count-time#17]
The statistics are not accurate. If there is code, it will be wrong. Several hundred words have changed into thousands

**Comment by ivan-nginx** [comment]
Can you give some example on this? Screenshots maybe?

**Comment by Love-H** [comment]
Hello, Mr. Ewan-nginx. First of all, please accept my sincere apology.Because I am not familiar with github and gmail is not my commonly used email, I just saw your reply to my question recently. I am really sorry!



Ok, let's get to the point. Let me start with my configuration,

- hexo versions

![](https://upload-images.jianshu.io/upload_images/14065724-fd7ea6dfab9e79a4.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

- hexo plug-in
  ![](https://upload-images.jianshu.io/upload_images/14065724-018e5537f2388b84.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

- symbols-count-time versions

![](https://upload-images.jianshu.io/upload_images/14065724-a85413d93d7228dc.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

- `_config.yml` configuration

![](https://upload-images.jianshu.io/upload_images/14065724-eaf29eec23fb6784.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)



### This is an article in hexo I use ` count_time ` counted the number of words

![](https://upload-images.jianshu.io/upload_images/14065724-76f8ce8a3a70abf3.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### The picture is my ` Typora ` software on statistical figures

![](https://upload-images.jianshu.io/upload_images/14065724-0f678a5cdb44fbb4.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### The picture is my ` Office 2016 ` software on statistical figures

![](https://upload-images.jianshu.io/upload_images/14065724-8637f10aada564dd.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### The obvious version

![](https://upload-images.jianshu.io/upload_images/14065724-c2dc11acca3a5bba.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/14065724-fe81be6fb0dcfd6c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### Finally, I saw you write in your blog

![](https://upload-images.jianshu.io/upload_images/14065724-ae94c4b8e6c46052.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### So I tried to modify the AWL parameters as follows:

![](https://upload-images.jianshu.io/upload_images/14065724-4021795b1fc53000.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### But it doesn't seem to work. Maybe I misunderstand what you mean...

![](https://upload-images.jianshu.io/upload_images/14065724-aa6ed0a08d09fb49.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by Love-H** [comment]
If you need more information, I will do my best.
