### ISSUE TITLE
统计不准确

### ISSUE THREAD

**Issue by Lruihao** [theme-next/hexo-symbols-count-time#19]
hexo-wordcount插件统计全站只有66k,这个插件确有200k,有一篇文章我用微软的word统计400字，这个插件确有7.7k之多

**Comment by stevenjoezhang** [comment]
能否提供更多信息？比如这篇文章的内容？

**Comment by DaveXuYuanfu** [comment]
确实不准确，在word里1500字不到，统计出来3000字。请问是跟  awl: 4
  wpm: 275这两个字段有关么

**Comment by ivan-nginx** [comment]
Duplicate of #17.
