### ISSUE TITLE
我尝试修改了站点配置文件和主题yml,但是底部还是无法显示字数统计，求解！

### ISSUE THREAD

**Issue by Skytostop** [theme-next/hexo-symbols-count-time#20]
config.yml如下
`symbols_count_time:`
`symbols: true`
`time: true`
`total_symbols: true`
`total_time: true`

next下yml如下
symbols_count_time:
  separated_meta: false
  item_text_post: false
  item_text_total: true
  awl: 2
  wpm: 300

但是底部死活不显示呀，我怀疑是之前误删除了swig里什么东西么
地址：qiubugu.com

**Comment by Skytostop** [comment]
改成这样好像又好了，不能都是true么

symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: false

**Comment by sli1989** [comment]
https://github.com/theme-next/hexo-theme-next/blob/bb5cfe650cb5de268633eb4a47ad575e37f55175/layout/_partials/footer.swig#L13-L38

so need u detailed steps to reproduce.
did you use `hexo clean`?

`config.symbols_count_time.total_symbols` is true and `theme.symbols_count_time.item_text_total` is true can show the site's total symbols in footer
