### ISSUE TITLE
 本文字数： 0 |  阅读时长 ≈ 1 分钟

### ISSUE THREAD

**Issue by suenyu** [theme-next/hexo-symbols-count-time#31]
状况：
每篇文章均： 本文字数： 0 |  阅读时长 ≈ 1 分钟
页脚字数统计时长统计正常。

Hexo version 3.8.0
Next version 7.1.1

已$ npm install hexo-symbols-count-time --save

hexo's _config.yml已填写，顶格，空格无误，值无误
NexT config已填写，顶格，空格无误，值无误
clean g 过，均无效

求解，谢谢！

**Comment by stevenjoezhang** [comment]
最近改了逻辑，NexT 7.1.1版本会出现问题。解决方案是：
- 使用最新的NexT master分支
- 或者，等待NexT 7.2.0版本发布
- 或者，卸载`hexo-symbols-count-time`的最新版本，然后安装0.5.0版本

**Comment by suenyu** [comment]
感谢!
回0.5.0，已正常。

**Comment by xfdj** [comment]
更新了Hexo和NexT之后我也出现了类似问题，我卸载了`hexo-symbols-count-time`（@0.6.0），然后安装了最新版本（同样是@0.6.0），问题就莫名其妙地解决了。
我的环境：
- Hexo v3.9.0
- NexT.Mist v7.2.0
- Hexo-cli v2.0.0
