### ISSUE TITLE
Wrong reading time display 

### ISSUE THREAD

**Issue by JERE-MIAH** [theme-next/hexo-symbols-count-time#4]
Hi, there is a little problem with my post's display, it display my article with thousands words can be read in seconds.
![image](https://user-images.githubusercontent.com/27946117/35065921-a62c9af2-fb83-11e7-8bd1-494cc3b43a3d.png)

**Comment by JERE-MIAH** [comment]
By the way, appreciate for your attribution to the next theme so much, I have already change my version to 6.01, that's amazing

**Comment by ivan-nginx** [comment]
This is not seconds, it minutes: 0:03 » 0 hours 03 minutes.

**Comment by JERE-MIAH** [comment]
I'm sorry, I will close the issue, thank you
