### ISSUE TITLE
The symbols count is undefined and reading time is NaN:aN.

### ISSUE THREAD

**Issue by HanielF** [theme-next/hexo-symbols-count-time#53]
## Environment:
- node: 12.11.0
- hexo: 3.9.0
- hexo-cli: 2.0.0
- NexT: 7.4.1

After hexo-symbols-count-time was installed, i found that the symbols count is undefined and reading time is NaN:aN. 
I searched the Issues but cannot find the answer.

So, Is there something wrong in my config file?

## Expected behavior:
![image](https://user-images.githubusercontent.com/24732516/66251887-efb92400-e787-11e9-85ad-982ffc957c25.png)

## Actual behavior:
![image](https://user-images.githubusercontent.com/24732516/66251900-14150080-e788-11e9-88af-ab0d82e119af.png)

**Comment by ningyuv** [comment]
the same problem to me.

**Comment by stevenjoezhang** [comment]
Run `hexo clean`

**Comment by HanielF** [comment]
@stevenjoezhang I've tried to run `hexo clean` and regenerate, but it has no change.

**Comment by ningyuv** [comment]
> Run `hexo clean`

it work

**Comment by HanielF** [comment]
@stevenjoezhang Oh, after two redoes, it works! Thank you!
