### ISSUE TITLE
按照说明一步一步安装后，执行 hexo clean && hexo -g 报错 当前hexo-v4.0.0 主题 – NexT.Gemini v7.5.0

### ISSUE THREAD

**Issue by Azjhong** [theme-next/hexo-symbols-count-time#61]
![Snipaste_2019-11-23_12-07-17](https://user-images.githubusercontent.com/46050133/69472884-869a7800-0dea-11ea-8bf1-e98eab0167cb.png)

**Comment by stevenjoezhang** [comment]
报错信息无意义。请提供源代码。

**Comment by kfbixc** [comment]
你好，当前hexo-v4.2.0 主题 – NexT.Gemini v7.7.1 执行 hexo clean && hexo -g 报同样的错 ，你解决了吗？如何解决的？

**Comment by stevenjoezhang** [comment]
如果在一个全新安装、没有作任何自定义的主题中复现了此问题，可以提供一下博客的源代码，我们可以帮助debug。

**Comment by kfbixc** [comment]
[test_symbols_count_time.zip](https://github.com/theme-next/hexo-symbols-count-time/files/4168877/test_symbols_count_time.zip)

Ubuntu 18.04上执行：hexo init test_symbols_count_time，然后修改hexo主题为next，将主题scheme: Gemini，其它的什么都没有修改，复现了，上面是博客源代码。

**Comment by stevenjoezhang** [comment]
你是怎么安装的？`hexo-symbols-count-time` 并没有出现在你的`package.json`中，但出现在了`node_modules`中。能否提供你所使用的Node.js和npm的版本？

**Comment by kfbixc** [comment]
hexo-symbols-count-time是我第一次建站的时候下载的，为了复现这个问题，我重新建了一个test-symbols-count-time路径，然后在这个路径下重新安装了一下hexo-symbols-count-time。
![hexo-symbols-count-time](https://user-images.githubusercontent.com/12266249/74002829-6458d500-49ab-11ea-92d0-a543ad5bb7b6.png)
root@kfb:~/test_symbols_count_time# npm -v
3.5.2
root@kfb:~/test_symbols_count_time# node -v
v8.10.0

**Comment by stevenjoezhang** [comment]
你的npm和node版本都严重过时了（目前官方支持的最低版本是Node.js 10）。你可以尝试升级Node和npm，或者使用如下命令重新安装插件：
```
npm install hexo-symbols-count-time --save
```
对于较新版本的npm，`--save`是默认的，所以README中没有写。

**Comment by kfbixc** [comment]
更新了最新的node和npm，现在正常了，感谢您的帮助，谢谢！

**Comment by stevenjoezhang** [comment]
不客气，有其它问题欢迎提出。祝您使用愉快！
