### ISSUE TITLE
bug: `suffix` config not functioning

### ISSUE THREAD

**Issue by bambooom** [theme-next/hexo-symbols-count-time#77]
I add `suffix` config like this:
```
symbols_count_time
  symbols: true
  time: true
  suffix: min read  
```

The rendered result is still `13 mins.`.

**Comment by stevenjoezhang** [comment]
Please use according to our documentation: https://github.com/theme-next/hexo-symbols-count-time#usage
There is no suffix setting here.

**Comment by bambooom** [comment]
Sorry, I misunderstood the doc. Then can I request `suffix` option in config?

**Comment by bambooom** [comment]
And the readme has this part:
![Screenshot 2020-01-27 at 5 26 47 PM](https://user-images.githubusercontent.com/14840170/73163105-38775d00-412a-11ea-8832-8de375117a2d.png)

Which made me think `awl` `wpm` and `suffix` are all available in config. 
Maybe you need to modify the readme to clarify that. Thanks.

**Comment by stevenjoezhang** [comment]
Thank you for pointing out the problem, this plugin only generates data, and the display & translation of `suffix` is controlled by the theme. If you are using theme NexT, you need to edit the relevant files in the `languages` folder

<img width="569" alt="截屏2020-01-27下午5 32 28" src="https://user-images.githubusercontent.com/16272760/73163471-0c101080-412b-11ea-92ea-fc9836a4ee8c.png">

**Comment by stevenjoezhang** [comment]
In fact the documentation is correct. The parameters here refer to the parameters in the theme's template file, not in the configuration file. We will consider modifying the order of the documents to avoid ambiguity.

**Comment by bambooom** [comment]
Thank you for the explanation. I'm not using NexT theme, so I guess I need to try other solutions.
