### ISSUE TITLE
字数统计阅读时长等没有随语言变化-symbols_count 、symbols_time and so on didn't change when language change

### ISSUE THREAD

**Issue by fengkx** [theme-next/hexo-symbols-count-time#8]
字数统计阅读时长等没有随语言变化
symbols_count 、symbols_time and so on didn't change when language change

它总是用的英文（languages/_en.yml)
It always uses the English version（languages/_en.yml)

**Comment by HillBamboo** [comment]
请问 问题是怎样解决的？我遇到了同样的问题：

![image](https://user-images.githubusercontent.com/10396980/61507410-32385380-aa18-11e9-861d-c1a1f0883835.png)

望告知，谢谢！

**Comment by HillBamboo** [comment]
@stevenjoezhang I already solved it by set `language : zh-CN`. Thank you 😄
