### ISSUE TITLE
Duplicate value when using hexo datafiles

### ISSUE THREAD

**Issue by maddovr** [theme-next/hexo-symbols-count-time#9]
Joining both hexo and next _config.yml in a single file causes a duplicate `symbols_count_time`, thus throwing an error. Is it possible to change the name of the next variable?

**Comment by ivan-nginx** [comment]
2 spaces indents. It's mean, in Hexo — 2 spaces; in NexT — +2 spaces — 4 spaces.

**Comment by maddovr** [comment]
Worked ty!
